export default class Questionnaire {
    key?: string | null;
    familyName: string;
    firstName: string;
    b00: string;
    course: string;
    projectChoice1: string;
    projectChoice2: string;
    projectChoice3: string;
    leader: string;
    pastCourses: string;
    studentRep: string;
    ipNDA: string;
    pastRemote: string;
    improve: string;
    acc: string;
    operatingSystem: string;
    backgroundEX: string;
    pastAgileSoft: string;
    pastGitEX: string;
    pastAgileScrum: string;
    pastAngular: string;
    pastReact: string;
    pastNext: string;
    pastFlutter: string;
    pastFirebase: string;
    pastAzure: string;
    pastAEM: string;
    pastHTMLCSS: string;
    pastPHP: string;
    pastWire: string;
    pastAnimation: string;
    pastReality: string;
    timeZone: string;
  }