name: Firebase deploy for X691 webapp
# https://github.com/google-github-actions/setup-gcloud
on:
  push:
    branches:
      - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy -- only hosting
        env:
          FIREBASE_TOKEN: 1:515129911876:web:636e82fa7c7cddc4cdaa11
